spring:
  application:
    name: api-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: produto-service
#          uri: lb://produto-ms
#          predicates:
#            - Path=/produto/**
#          filters:
#            - RewritePath=/produto/(?<path>.*), /$\{path}
server:
  port: 8766
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      .defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true