spring:
  application:
    name: api-gateway
server:
  port: 8765
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      .defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#zuul:
#  routes:
#    convert-service:
#      path: /api-eureka-server/**
#      stripPrefix: false
#  sensitive-headers:
#    - Cookie
zuul:
  routes:
    produto:
      serviceId: http://localhost:8081
      path: /produto-ms/**
      stripPrefix: false




#spring.application.name=api-gateway-zuul
#server.port=8765
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#
##Mapeando os microsservicos que iram usar o gateway
##zuul.routes.produto-ms.service.url=http://localhost:8081
#zuul.routes.produto.serviceId=produto-ms
#zuul.routes.produto.path=/produto-ms/**
##zuul.routes.produto-ms.strip-prefix=false

#spring.main.allow-bean-definition-overriding=true
#spring.main.allow-circular-references=true
